import { Project } from './types';

export const SAMPLE_PROJECT: Project = {
  id: 'proj-sample-electrical',
  name: 'Commercial Medical Center - Division 26 Package',
  createdAt: new Date().toISOString(),
  status: 'ready',
  processingSteps: [
    { id: '1', label: 'Documents uploaded', status: 'completed', details: '2 PDF document packages loaded' },
    { id: '2', label: 'PDF text extraction & OCR', status: 'completed', details: 'Extracted 5 sheets & specifications' },
    { id: '3', label: 'Sheets & schedules identified', status: 'completed', details: 'Single-line diagram & schedules matched' },
    { id: '4', label: 'Specifications indexed', status: 'completed', details: 'Division 26 24 16, 26 28 16 indexed' },
    { id: '5', label: 'Drawing + specification cross-check', status: 'completed', details: '3 scope discrepancies identified for estimator review' },
  ],
  documents: [
    {
      id: 'doc-sample-dwg-1',
      projectId: 'proj-sample-electrical',
      name: 'E1.1_Power_Single_Line_Diagram.pdf',
      category: 'drawing',
      fileSize: 452000,
      uploadedAt: new Date().toISOString(),
      pageCount: 2,
      status: 'ready',
      pages: [
        {
          pageNumber: 1,
          sheetOrSection: 'Sheet E1.1',
          title: 'Power Single-Line Diagram & Feeder Schedules',
          text: 'SHEET E1.1 - POWER DISTRIBUTION SINGLE LINE DIAGRAM. Main Service Switchboard MSB-1: 2000A, 480Y/277V, 3-Phase, 4-Wire. Feeder Note 4: Feeder sizes indicated on single-line diagram are based on standard aluminum conductor ratings unless specifically tagged Cu. Feeder to RTU-1 feeds directly from Distribution Panelboard DP-1 to junction box. No local external disconnect switch symbol shown. Panel schedules denote aluminum bussing for branch panels A & B.',
        },
        {
          pageNumber: 2,
          sheetOrSection: 'Sheet E2.1',
          title: 'Panel Schedules & General Electrical Notes',
          text: 'SHEET E2.1 - PANEL SCHEDULES. Panelboard A: 225A, 208Y/120V, 42 circuits. Note 2: Contractor to balance phase loads and provide engraved phenolic nameplates for all panels. Lighting branch circuits denote standard wall switches without daylight photocell sensor symbols on perimeter glazing.',
        },
      ],
    },
    {
      id: 'doc-sample-spec-1',
      projectId: 'proj-sample-electrical',
      name: 'Division_26_Electrical_Specifications.pdf',
      category: 'specification',
      fileSize: 685000,
      uploadedAt: new Date().toISOString(),
      pageCount: 3,
      status: 'ready',
      pages: [
        {
          pageNumber: 1,
          sheetOrSection: 'Section 26 24 16',
          title: 'Panelboards - Part 2 Products',
          text: 'SECTION 26 24 16 - PANELBOARDS. 2.01 BUS METALLURGY: All bus bars, phase conductors, and neutral buses shall be 98% conductivity electrolytic copper. Aluminum bussing or conductors will not be accepted without written approval from engineer of record.',
        },
        {
          pageNumber: 2,
          sheetOrSection: 'Section 26 28 16',
          title: 'Enclosed Switches - Part 3 Execution',
          text: 'SECTION 26 28 16 - SAFETY SWITCHES. 3.01 MECHANICAL DISCONNECTS: Contractor shall furnish and install heavy-duty NEMA 3R/4X lockable disconnect switches within line-of-sight (max 50 ft) of all packaged mechanical HVAC units, pumps, and exhaust fans.',
        },
        {
          pageNumber: 3,
          sheetOrSection: 'Section 26 09 23',
          title: 'Lighting Control Devices - Part 2 Products',
          text: 'SECTION 26 09 23 - LIGHTING CONTROLS. 2.02 SENSORS: Provide continuous 0-10V dimming daylight harvesting photocells in all primary sidelit daylight zones conforming to ASHRAE 90.1 / IECC requirements within 15 feet of exterior glazing.',
        },
      ],
    },
  ],
  findings: [
    {
      id: 'finding-sample-1',
      projectId: 'proj-sample-electrical',
      title: 'Panelboard Bussing & Conductor Metallurgy Discrepancy',
      type: 'CONFLICT',
      confidence: 'HIGH',
      confidenceRationale: 'Direct discrepancy between Division 26 specification metallurgy and drawing feeder notes.',
      systemArea: 'Power Distribution',
      explanation: 'Specification Section 26 24 16 strictly requires 100% copper bussing and copper conductors for all main switchboards and distribution panelboards. Drawing Sheet E1.1 schedules and feeder notes specify standard aluminum (AL) conductors.',
      sourceA: {
        id: 'ev-a-sample-1',
        type: 'specification',
        documentId: 'doc-spec-1',
        documentName: 'Division_26_Electrical_Specifications.pdf',
        sectionNumber: 'Section 26 24 16',
        pageNumber: 1,
        location: 'Part 2 - Products, 2.01 Bus Metallurgy',
        relevantText: 'All bus bars, phase conductors, and neutral buses shall be 98% conductivity electrolytic copper. Aluminum bussing or conductors will not be accepted without written approval.',
        highlightSnippet: 'All bus bars... shall be 98% conductivity electrolytic copper. Aluminum... will not be accepted.',
      },
      sourceB: {
        id: 'ev-b-sample-1',
        type: 'drawing',
        documentId: 'doc-sample-dwg-1',
        documentName: 'E1.1_Power_Single_Line_Diagram.pdf',
        sheetNumber: 'Sheet E1.1',
        pageNumber: 1,
        location: 'Power Distribution Feeder Notes',
        relevantText: 'Feeder Note 4: Feeder sizes indicated on single-line diagram are based on standard aluminum conductor ratings unless specifically tagged Cu.',
        highlightSnippet: 'Feeder sizes indicated on single-line diagram are based on standard aluminum conductor ratings...',
      },
      status: 'PENDING',
      estimatorNotes: '',
    },
    {
      id: 'finding-sample-2',
      projectId: 'proj-sample-electrical',
      title: 'Mechanical Disconnect Switches Omitted on Plan Drawings',
      type: 'SCOPE_GAP',
      confidence: 'HIGH',
      confidenceRationale: 'Equipment schedule requires localized lockable disconnects, but single-line plan lacks individual safety switches.',
      systemArea: 'HVAC & Mechanical Coordination',
      explanation: 'Specification Section 26 28 16 mandates heavy-duty NEMA 3R/4X lockable safety disconnect switches within line-of-sight of all packaged rooftop units. Drawing Sheet E1.1 shows home run feeds directly to RTU-1 without an external disconnect switch symbol.',
      sourceA: {
        id: 'ev-a-sample-2',
        type: 'specification',
        documentId: 'doc-spec-1',
        documentName: 'Division_26_Electrical_Specifications.pdf',
        sectionNumber: 'Section 26 28 16',
        pageNumber: 2,
        location: 'Part 3 - Execution, 3.01 Mechanical Disconnects',
        relevantText: 'Contractor shall furnish and install heavy-duty NEMA 3R/4X lockable disconnect switches within line-of-sight (max 50 ft) of all packaged mechanical HVAC units, pumps, and exhaust fans.',
        highlightSnippet: 'install heavy-duty lockable disconnect switches within line-of-sight...',
      },
      sourceB: {
        id: 'ev-b-sample-2',
        type: 'drawing',
        documentId: 'doc-sample-dwg-1',
        documentName: 'E1.1_Power_Single_Line_Diagram.pdf',
        sheetNumber: 'Sheet E1.1',
        pageNumber: 1,
        location: 'Roof Power Plan & Feeder Schedule',
        relevantText: 'Feeder to RTU-1 feeds directly from Distribution Panelboard DP-1 to junction box. No local external disconnect switch symbol shown.',
        highlightSnippet: 'Feeder to RTU-1 feeds directly... No local external disconnect switch symbol shown.',
      },
      status: 'PENDING',
      estimatorNotes: '',
    },
    {
      id: 'finding-sample-3',
      projectId: 'proj-sample-electrical',
      title: 'Automatic Daylight Harvesting & Sensor Coverage Verification',
      type: 'DOCUMENT_CONFLICT',
      confidence: 'MEDIUM',
      confidenceRationale: 'Energy code compliance section requires 0-10V daylight dimming sensors, but floor plan specifies manual switching.',
      systemArea: 'Lighting Controls',
      explanation: 'Specification Section 26 09 23 mandates continuous daylight dimming photo-sensors for all perimeter zones within 15 feet of exterior glazing. Drawing Sheet E2.1 indicates standard manual wall toggle switches without sensor power packs.',
      sourceA: {
        id: 'ev-a-sample-3',
        type: 'specification',
        documentId: 'doc-spec-1',
        documentName: 'Division_26_Electrical_Specifications.pdf',
        sectionNumber: 'Section 26 09 23',
        pageNumber: 3,
        location: 'Part 2 - Lighting Control Devices, 2.02 Sensors',
        relevantText: 'Provide continuous 0-10V dimming daylight harvesting photocells in all primary sidelit daylight zones conforming to ASHRAE 90.1 / IECC requirements within 15 feet of exterior glazing.',
        highlightSnippet: 'Provide continuous 0-10V dimming daylight harvesting photocells in all primary sidelit daylight zones...',
      },
      sourceB: {
        id: 'ev-b-sample-3',
        type: 'drawing',
        documentId: 'doc-sample-dwg-1',
        documentName: 'E1.1_Power_Single_Line_Diagram.pdf',
        sheetNumber: 'Sheet E2.1',
        pageNumber: 2,
        location: 'Lighting Floor Plan & Fixture Legend',
        relevantText: 'Lighting branch circuits denote standard wall switches without daylight photocell sensor symbols on perimeter glazing.',
        highlightSnippet: 'denote standard wall switches without daylight photocell sensor symbols...',
      },
      status: 'PENDING',
      estimatorNotes: '',
    },
  ],
};

export const EMPTY_PROJECT: Project = {
  id: '',
  name: 'Lopri AI Workspace',
  createdAt: new Date().toISOString(),
  status: 'uploading',
  processingSteps: [
    { id: '1', label: 'Documents uploaded', status: 'pending' },
    { id: '2', label: 'PDF text extraction & OCR', status: 'pending' },
    { id: '3', label: 'Sheets & schedules identified', status: 'pending' },
    { id: '4', label: 'Specifications indexed', status: 'pending' },
    { id: '5', label: 'Drawing + specification cross-check', status: 'pending' },
  ],
  documents: [],
  findings: [],
};
